name: flutter_material_palette
description: An wrapper package around material_palette which can generate an full material design palette from an single color in a flutter compatible api
version: 0.1.0

environment:
  flutter: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_palette: ^0.1.0
  color_models: ^1.3.0
  flutter_color_models: ^1.3.0
