name: flutter_material_palette
description: An wrapper package around material_palette which can generate an full material design palette from an single color in a flutter compatible api
version: 0.2.1

environment:
  flutter: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_palette: ^0.2.1
  flutter_color_models: ^1.2.1
